// This file is @generated by prost-build.
/// ClassifiedTransaction — a pending mempool tx with pipeline classification.
/// Mirrors Go's pipeline.ClassifiedTx struct.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClassifiedTransaction {
    /// Keccak-256 transaction hash (32 bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    /// Sender address (20 bytes)
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    /// Recipient address (20 bytes, empty for creation)
    #[prost(bytes = "vec", tag = "3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// ETH value in wei (uint256 big-endian)
    #[prost(bytes = "vec", tag = "4")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// Gas price in gwei
    #[prost(uint64, tag = "5")]
    pub gas_price: u64,
    /// Maximum gas units
    #[prost(uint64, tag = "6")]
    pub gas_limit: u64,
    /// Raw ABI-encoded calldata
    #[prost(bytes = "vec", tag = "7")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    /// Sender nonce
    #[prost(uint64, tag = "8")]
    pub nonce: u64,
    /// Pipeline classification result
    #[prost(enumeration = "TxClass", tag = "9")]
    pub tx_class: i32,
    /// Decoded swap params (populated for swap txs)
    #[prost(message, optional, tag = "10")]
    pub swap_info: ::core::option::Option<SwapInfo>,
    /// Next block number from block watcher
    #[prost(uint64, tag = "11")]
    pub target_block: u64,
    /// Current base fee (uint256 big-endian)
    #[prost(bytes = "vec", tag = "12")]
    pub base_fee: ::prost::alloc::vec::Vec<u8>,
}
/// SwapInfo — decoded swap parameters from calldata.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapInfo {
    /// Input token amount (uint256 big-endian)
    #[prost(bytes = "vec", tag = "1")]
    pub amount_in: ::prost::alloc::vec::Vec<u8>,
    /// Minimum output (slippage bound, uint256)
    #[prost(bytes = "vec", tag = "2")]
    pub amount_out_min: ::prost::alloc::vec::Vec<u8>,
    /// Number of tokens in the swap path
    #[prost(uint32, tag = "3")]
    pub path_length: u32,
    /// Unix timestamp deadline
    #[prost(uint64, tag = "4")]
    pub deadline: u64,
}
/// DetectionResult — response from the Rust detection pipeline.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectionResult {
    /// Whether any MEV opportunities were found
    #[prost(bool, tag = "1")]
    pub found: bool,
    /// Detected opportunities with bundles
    #[prost(message, repeated, tag = "2")]
    pub opportunities: ::prost::alloc::vec::Vec<Opportunity>,
    /// End-to-end detection time in nanoseconds
    #[prost(uint64, tag = "3")]
    pub detection_latency_ns: u64,
}
/// Opportunity — a detected MEV opportunity with an optional pre-built bundle.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Opportunity {
    /// MEV strategy classification
    #[prost(enumeration = "OpportunityType", tag = "1")]
    pub r#type: i32,
    /// Input token address (hex)
    #[prost(string, tag = "2")]
    pub token_in: ::prost::alloc::string::String,
    /// Output token address (hex)
    #[prost(string, tag = "3")]
    pub token_out: ::prost::alloc::string::String,
    /// Flash loan / swap amount (uint256)
    #[prost(bytes = "vec", tag = "4")]
    pub amount_in: ::prost::alloc::vec::Vec<u8>,
    /// Estimated profit after gas (uint256)
    #[prost(bytes = "vec", tag = "5")]
    pub expected_profit: ::prost::alloc::vec::Vec<u8>,
    /// Estimated gas for the full bundle
    #[prost(uint64, tag = "6")]
    pub gas_estimate: u64,
    /// Pre-built Flashbots bundle (if simulation passed)
    #[prost(message, optional, tag = "7")]
    pub bundle: ::core::option::Option<Bundle>,
}
/// Bundle — ordered set of transactions for Flashbots relay submission.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bundle {
    /// Ordered transactions in the bundle
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<BundleTx>,
    /// Preferred inclusion block
    #[prost(uint64, tag = "2")]
    pub target_block: u64,
}
/// BundleTx — a single transaction within a Flashbots bundle.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BundleTx {
    /// Executor contract address (20 bytes)
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    /// ETH value (uint256, typically 0)
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    /// Gas limit for this tx
    #[prost(uint64, tag = "3")]
    pub gas_limit: u64,
    /// EIP-1559 max fee (uint256)
    #[prost(bytes = "vec", tag = "4")]
    pub max_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    /// Miner tip for bundle ordering (uint256)
    #[prost(bytes = "vec", tag = "5")]
    pub max_priority_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    /// ABI-encoded executor calldata
    #[prost(bytes = "vec", tag = "6")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
/// StreamRequest — subscribe to real-time opportunity stream.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRequest {
    /// Minimum profit threshold (wei, uint256 big-endian)
    #[prost(bytes = "vec", tag = "1")]
    pub min_profit: ::prost::alloc::vec::Vec<u8>,
}
/// StatusRequest — empty request for health check.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusRequest {}
/// StatusResponse — engine health and cumulative counters.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    /// Whether the engine is actively processing
    #[prost(bool, tag = "1")]
    pub running: bool,
    /// Total opportunities found since start
    #[prost(uint64, tag = "2")]
    pub opportunities_detected: u64,
    #[prost(uint64, tag = "3")]
    pub simulations_run: u64,
    #[prost(uint64, tag = "4")]
    pub bundles_built: u64,
    #[prost(uint64, tag = "5")]
    pub uptime_seconds: u64,
}
/// TxClass — transaction classification from the Go pipeline.
/// Enum values match pipeline.TxClass constants.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TxClass {
    /// Unrecognized selector
    Unknown = 0,
    /// UniswapV2-style swap (6 selectors)
    SwapV2 = 1,
    /// UniswapV3-style swap (4 selectors)
    SwapV3 = 2,
    /// ERC20 transfer/transferFrom
    Transfer = 3,
    /// ERC20 approve
    Approval = 4,
    /// Aave/Compound liquidation call
    Liquidation = 5,
    /// Flash loan initiation (Balancer/Aave)
    FlashLoan = 6,
}
impl TxClass {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            TxClass::Unknown => "UNKNOWN",
            TxClass::SwapV2 => "SWAP_V2",
            TxClass::SwapV3 => "SWAP_V3",
            TxClass::Transfer => "TRANSFER",
            TxClass::Approval => "APPROVAL",
            TxClass::Liquidation => "LIQUIDATION",
            TxClass::FlashLoan => "FLASH_LOAN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "SWAP_V2" => Some(Self::SwapV2),
            "SWAP_V3" => Some(Self::SwapV3),
            "TRANSFER" => Some(Self::Transfer),
            "APPROVAL" => Some(Self::Approval),
            "LIQUIDATION" => Some(Self::Liquidation),
            "FLASH_LOAN" => Some(Self::FlashLoan),
            _ => None,
        }
    }
}
/// OpportunityType — MEV strategy classification.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpportunityType {
    /// Cross-DEX price discrepancy
    Arbitrage = 0,
    /// Price recovery after large swap
    Backrun = 1,
    /// Under-collateralized position liquidation
    LiquidationOpp = 2,
}
impl OpportunityType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            OpportunityType::Arbitrage => "ARBITRAGE",
            OpportunityType::Backrun => "BACKRUN",
            OpportunityType::LiquidationOpp => "LIQUIDATION_OPP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARBITRAGE" => Some(Self::Arbitrage),
            "BACKRUN" => Some(Self::Backrun),
            "LIQUIDATION_OPP" => Some(Self::LiquidationOpp),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod mev_engine_client {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// MevEngine — the Rust core exposes this gRPC service.
    /// Go network layer streams classified transactions and receives
    /// detected opportunities with pre-built bundles.
    #[derive(Debug, Clone)]
    pub struct MevEngineClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl MevEngineClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> MevEngineClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> MevEngineClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + Send + Sync,
        {
            MevEngineClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Unary: send a single classified transaction, receive detection result
        pub async fn detect_opportunity(
            &mut self,
            request: impl tonic::IntoRequest<super::ClassifiedTransaction>,
        ) -> std::result::Result<
            tonic::Response<super::DetectionResult>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mev.MevEngine/DetectOpportunity",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mev.MevEngine", "DetectOpportunity"));
            self.inner.unary(req, path, codec).await
        }
        /// Server-streaming: subscribe to all detected opportunities in real time
        pub async fn stream_opportunities(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::DetectionResult>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/mev.MevEngine/StreamOpportunities",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("mev.MevEngine", "StreamOpportunities"));
            self.inner.server_streaming(req, path, codec).await
        }
        /// Health/stats endpoint
        pub async fn get_status(
            &mut self,
            request: impl tonic::IntoRequest<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::new(
                        tonic::Code::Unknown,
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/mev.MevEngine/GetStatus");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("mev.MevEngine", "GetStatus"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod mev_engine_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with MevEngineServer.
    #[async_trait]
    pub trait MevEngine: Send + Sync + 'static {
        /// Unary: send a single classified transaction, receive detection result
        async fn detect_opportunity(
            &self,
            request: tonic::Request<super::ClassifiedTransaction>,
        ) -> std::result::Result<tonic::Response<super::DetectionResult>, tonic::Status>;
        /// Server streaming response type for the StreamOpportunities method.
        type StreamOpportunitiesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::DetectionResult, tonic::Status>,
            >
            + Send
            + 'static;
        /// Server-streaming: subscribe to all detected opportunities in real time
        async fn stream_opportunities(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamOpportunitiesStream>,
            tonic::Status,
        >;
        /// Health/stats endpoint
        async fn get_status(
            &self,
            request: tonic::Request<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>;
    }
    /// MevEngine — the Rust core exposes this gRPC service.
    /// Go network layer streams classified transactions and receives
    /// detected opportunities with pre-built bundles.
    #[derive(Debug)]
    pub struct MevEngineServer<T: MevEngine> {
        inner: _Inner<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    struct _Inner<T>(Arc<T>);
    impl<T: MevEngine> MevEngineServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            let inner = _Inner(inner);
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for MevEngineServer<T>
    where
        T: MevEngine,
        B: Body + Send + 'static,
        B::Error: Into<StdError> + Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            let inner = self.inner.clone();
            match req.uri().path() {
                "/mev.MevEngine/DetectOpportunity" => {
                    #[allow(non_camel_case_types)]
                    struct DetectOpportunitySvc<T: MevEngine>(pub Arc<T>);
                    impl<
                        T: MevEngine,
                    > tonic::server::UnaryService<super::ClassifiedTransaction>
                    for DetectOpportunitySvc<T> {
                        type Response = super::DetectionResult;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ClassifiedTransaction>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MevEngine>::detect_opportunity(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = DetectOpportunitySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/mev.MevEngine/StreamOpportunities" => {
                    #[allow(non_camel_case_types)]
                    struct StreamOpportunitiesSvc<T: MevEngine>(pub Arc<T>);
                    impl<
                        T: MevEngine,
                    > tonic::server::ServerStreamingService<super::StreamRequest>
                    for StreamOpportunitiesSvc<T> {
                        type Response = super::DetectionResult;
                        type ResponseStream = T::StreamOpportunitiesStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MevEngine>::stream_opportunities(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = StreamOpportunitiesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/mev.MevEngine/GetStatus" => {
                    #[allow(non_camel_case_types)]
                    struct GetStatusSvc<T: MevEngine>(pub Arc<T>);
                    impl<T: MevEngine> tonic::server::UnaryService<super::StatusRequest>
                    for GetStatusSvc<T> {
                        type Response = super::StatusResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StatusRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as MevEngine>::get_status(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let inner = inner.0;
                        let method = GetStatusSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        Ok(
                            http::Response::builder()
                                .status(200)
                                .header("grpc-status", "12")
                                .header("content-type", "application/grpc")
                                .body(empty_body())
                                .unwrap(),
                        )
                    })
                }
            }
        }
    }
    impl<T: MevEngine> Clone for MevEngineServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    impl<T: MevEngine> Clone for _Inner<T> {
        fn clone(&self) -> Self {
            Self(Arc::clone(&self.0))
        }
    }
    impl<T: std::fmt::Debug> std::fmt::Debug for _Inner<T> {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{:?}", self.0)
        }
    }
    impl<T: MevEngine> tonic::server::NamedService for MevEngineServer<T> {
        const NAME: &'static str = "mev.MevEngine";
    }
}
