// @generated by tonic-build. Do not edit.
// source: mev.proto

/// Classified transaction from Go pipeline
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClassifiedTransaction {
    #[prost(bytes = "vec", tag = "1")]
    pub tx_hash: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub from: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub gas_price: u64,
    #[prost(uint64, tag = "6")]
    pub gas_limit: u64,
    #[prost(bytes = "vec", tag = "7")]
    pub input: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "8")]
    pub nonce: u64,
    #[prost(enumeration = "TxClass", tag = "9")]
    pub tx_class: i32,
    #[prost(message, optional, tag = "10")]
    pub swap_info: ::core::option::Option<SwapInfo>,
    #[prost(uint64, tag = "11")]
    pub target_block: u64,
    #[prost(bytes = "vec", tag = "12")]
    pub base_fee: ::prost::alloc::vec::Vec<u8>,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapInfo {
    #[prost(bytes = "vec", tag = "1")]
    pub amount_in: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub amount_out_min: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint32, tag = "3")]
    pub path_length: u32,
    #[prost(uint64, tag = "4")]
    pub deadline: u64,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DetectionResult {
    #[prost(bool, tag = "1")]
    pub found: bool,
    #[prost(message, repeated, tag = "2")]
    pub opportunities: ::prost::alloc::vec::Vec<Opportunity>,
    #[prost(uint64, tag = "3")]
    pub detection_latency_ns: u64,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Opportunity {
    #[prost(enumeration = "OpportunityType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub token_in: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub token_out: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "4")]
    pub amount_in: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub expected_profit: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "6")]
    pub gas_estimate: u64,
    #[prost(message, optional, tag = "7")]
    pub bundle: ::core::option::Option<Bundle>,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bundle {
    #[prost(message, repeated, tag = "1")]
    pub transactions: ::prost::alloc::vec::Vec<BundleTx>,
    #[prost(uint64, tag = "2")]
    pub target_block: u64,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BundleTx {
    #[prost(bytes = "vec", tag = "1")]
    pub to: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "3")]
    pub gas_limit: u64,
    #[prost(bytes = "vec", tag = "4")]
    pub max_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "5")]
    pub max_priority_fee_per_gas: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "6")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StreamRequest {
    #[prost(bytes = "vec", tag = "1")]
    pub min_profit: ::prost::alloc::vec::Vec<u8>,
}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusRequest {}

#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StatusResponse {
    #[prost(bool, tag = "1")]
    pub running: bool,
    #[prost(uint64, tag = "2")]
    pub opportunities_detected: u64,
    #[prost(uint64, tag = "3")]
    pub simulations_run: u64,
    #[prost(uint64, tag = "4")]
    pub bundles_built: u64,
    #[prost(uint64, tag = "5")]
    pub uptime_seconds: u64,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TxClass {
    Unknown = 0,
    SwapV2 = 1,
    SwapV3 = 2,
    Transfer = 3,
    Approval = 4,
    Liquidation = 5,
    FlashLoan = 6,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OpportunityType {
    Arbitrage = 0,
    Backrun = 1,
    LiquidationOpp = 2,
}

/// Generated server implementations.
pub mod mev_engine_server {
    #![allow(unused_variables, dead_code, missing_docs, clippy::let_unit_value)]
    use tonic::codegen::*;

    /// Generated trait for MevEngine service.
    #[async_trait]
    pub trait MevEngine: Send + Sync + 'static {
        async fn detect_opportunity(
            &self,
            request: tonic::Request<super::ClassifiedTransaction>,
        ) -> std::result::Result<tonic::Response<super::DetectionResult>, tonic::Status>;

        type StreamOpportunitiesStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::DetectionResult, tonic::Status>,
            > + Send
            + 'static;

        async fn stream_opportunities(
            &self,
            request: tonic::Request<super::StreamRequest>,
        ) -> std::result::Result<tonic::Response<Self::StreamOpportunitiesStream>, tonic::Status>;

        async fn get_status(
            &self,
            request: tonic::Request<super::StatusRequest>,
        ) -> std::result::Result<tonic::Response<super::StatusResponse>, tonic::Status>;
    }

    #[derive(Debug)]
    pub struct MevEngineServer<T: MevEngine> {
        inner: Arc<T>,
    }

    impl<T: MevEngine> MevEngineServer<T> {
        pub fn new(inner: T) -> Self {
            Self {
                inner: Arc::new(inner),
            }
        }

        pub fn from_arc(inner: Arc<T>) -> Self {
            Self { inner }
        }
    }

    impl<T: MevEngine> Clone for MevEngineServer<T> {
        fn clone(&self) -> Self {
            Self {
                inner: self.inner.clone(),
            }
        }
    }
}
