name: Bug report
description: Report a reproducible defect
title: "[Bug]: "
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Clear and concise description of the bug
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Provide exact steps and commands
      placeholder: |
        1. Run ...
        2. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: OS, toolchain versions, commit hash

  - type: textarea
    id: logs
    attributes:
      label: Logs / traces
      render: shell