// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mev.proto

package proto

// TxClass enum
type TxClass int32

const (
	TxClass_UNKNOWN     TxClass = 0
	TxClass_SWAP_V2     TxClass = 1
	TxClass_SWAP_V3     TxClass = 2
	TxClass_TRANSFER    TxClass = 3
	TxClass_APPROVAL    TxClass = 4
	TxClass_LIQUIDATION TxClass = 5
	TxClass_FLASH_LOAN  TxClass = 6
)

// OpportunityType enum
type OpportunityType int32

const (
	OpportunityType_ARBITRAGE       OpportunityType = 0
	OpportunityType_BACKRUN         OpportunityType = 1
	OpportunityType_LIQUIDATION_OPP OpportunityType = 2
)

// ClassifiedTransaction is a pending tx with classification from the Go pipeline.
type ClassifiedTransaction struct {
	TxHash      []byte    `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	From        []byte    `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To          []byte    `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value       []byte    `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	GasPrice    uint64    `protobuf:"varint,5,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit    uint64    `protobuf:"varint,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	Input       []byte    `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	Nonce       uint64    `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TxClass     TxClass   `protobuf:"varint,9,opt,name=tx_class,json=txClass,proto3,enum=mev.TxClass" json:"tx_class,omitempty"`
	SwapInfo    *SwapInfo `protobuf:"bytes,10,opt,name=swap_info,json=swapInfo,proto3" json:"swap_info,omitempty"`
	TargetBlock uint64    `protobuf:"varint,11,opt,name=target_block,json=targetBlock,proto3" json:"target_block,omitempty"`
	BaseFee     []byte    `protobuf:"bytes,12,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
}

// SwapInfo contains decoded swap parameters.
type SwapInfo struct {
	AmountIn     []byte `protobuf:"bytes,1,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	AmountOutMin []byte `protobuf:"bytes,2,opt,name=amount_out_min,json=amountOutMin,proto3" json:"amount_out_min,omitempty"`
	PathLength   uint32 `protobuf:"varint,3,opt,name=path_length,json=pathLength,proto3" json:"path_length,omitempty"`
	Deadline     uint64 `protobuf:"varint,4,opt,name=deadline,proto3" json:"deadline,omitempty"`
}

// DetectionResult returned by the Rust core.
type DetectionResult struct {
	Found              bool           `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Opportunities      []*Opportunity `protobuf:"bytes,2,rep,name=opportunities,proto3" json:"opportunities,omitempty"`
	DetectionLatencyNs uint64         `protobuf:"varint,3,opt,name=detection_latency_ns,json=detectionLatencyNs,proto3" json:"detection_latency_ns,omitempty"`
}

// Opportunity represents a detected MEV opportunity.
type Opportunity struct {
	Type           OpportunityType `protobuf:"varint,1,opt,name=type,proto3,enum=mev.OpportunityType" json:"type,omitempty"`
	TokenIn        string          `protobuf:"bytes,2,opt,name=token_in,json=tokenIn,proto3" json:"token_in,omitempty"`
	TokenOut       string          `protobuf:"bytes,3,opt,name=token_out,json=tokenOut,proto3" json:"token_out,omitempty"`
	AmountIn       []byte          `protobuf:"bytes,4,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	ExpectedProfit []byte          `protobuf:"bytes,5,opt,name=expected_profit,json=expectedProfit,proto3" json:"expected_profit,omitempty"`
	GasEstimate    uint64          `protobuf:"varint,6,opt,name=gas_estimate,json=gasEstimate,proto3" json:"gas_estimate,omitempty"`
	Bundle         *Bundle         `protobuf:"bytes,7,opt,name=bundle,proto3" json:"bundle,omitempty"`
}

// Bundle to be submitted to Flashbots relay.
type Bundle struct {
	Transactions []*BundleTx `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	TargetBlock  uint64      `protobuf:"varint,2,opt,name=target_block,json=targetBlock,proto3" json:"target_block,omitempty"`
}

// BundleTx is a single transaction within a bundle.
type BundleTx struct {
	To                   []byte `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Value                []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	GasLimit             uint64 `protobuf:"varint,3,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	MaxFeePerGas         []byte `protobuf:"bytes,4,opt,name=max_fee_per_gas,json=maxFeePerGas,proto3" json:"max_fee_per_gas,omitempty"`
	MaxPriorityFeePerGas []byte `protobuf:"bytes,5,opt,name=max_priority_fee_per_gas,json=maxPriorityFeePerGas,proto3" json:"max_priority_fee_per_gas,omitempty"`
	Data                 []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
}

// StreamRequest for the streaming RPC.
type StreamRequest struct {
	MinProfit []byte `protobuf:"bytes,1,opt,name=min_profit,json=minProfit,proto3" json:"min_profit,omitempty"`
}

// StatusRequest for health check.
type StatusRequest struct{}

// StatusResponse from engine health check.
type StatusResponse struct {
	Running               bool   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	OpportunitiesDetected uint64 `protobuf:"varint,2,opt,name=opportunities_detected,json=opportunitiesDetected,proto3" json:"opportunities_detected,omitempty"`
	SimulationsRun        uint64 `protobuf:"varint,3,opt,name=simulations_run,json=simulationsRun,proto3" json:"simulations_run,omitempty"`
	BundlesBuilt          uint64 `protobuf:"varint,4,opt,name=bundles_built,json=bundlesBuilt,proto3" json:"bundles_built,omitempty"`
	UptimeSeconds         uint64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
}
