// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: mev.proto

package proto

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// MevEngineClient is the client API for MevEngine service.
type MevEngineClient interface {
	DetectOpportunity(ctx context.Context, in *ClassifiedTransaction, opts ...grpc.CallOption) (*DetectionResult, error)
	GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type mevEngineClient struct {
	cc grpc.ClientConnInterface
}

// NewMevEngineClient creates a new gRPC client for the Rust MEV core.
func NewMevEngineClient(cc grpc.ClientConnInterface) MevEngineClient {
	return &mevEngineClient{cc}
}

const (
	mevEngineDetectMethod = "/mev.MevEngine/DetectOpportunity"
	mevEngineStatusMethod = "/mev.MevEngine/GetStatus"
)

func (c *mevEngineClient) DetectOpportunity(ctx context.Context, in *ClassifiedTransaction, opts ...grpc.CallOption) (*DetectionResult, error) {
	out := new(DetectionResult)
	err := c.cc.Invoke(ctx, mevEngineDetectMethod, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mevEngineClient) GetStatus(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, mevEngineStatusMethod, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MevEngineServer is the server API for MevEngine service.
type MevEngineServer interface {
	DetectOpportunity(context.Context, *ClassifiedTransaction) (*DetectionResult, error)
	GetStatus(context.Context, *StatusRequest) (*StatusResponse, error)
}

// UnimplementedMevEngineServer should be embedded to have forward compatible implementations.
type UnimplementedMevEngineServer struct{}

func (UnimplementedMevEngineServer) DetectOpportunity(context.Context, *ClassifiedTransaction) (*DetectionResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetectOpportunity not implemented")
}

func (UnimplementedMevEngineServer) GetStatus(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}

// RegisterMevEngineServer registers the service with a gRPC server.
func RegisterMevEngineServer(s grpc.ServiceRegistrar, srv MevEngineServer) {
	s.RegisterService(&MevEngine_ServiceDesc, srv)
}

// MevEngine_ServiceDesc is the grpc.ServiceDesc for MevEngine service.
var MevEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mev.MevEngine",
	HandlerType: (*MevEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DetectOpportunity",
			Handler:    _MevEngine_DetectOpportunity_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _MevEngine_GetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mev.proto",
}

func _MevEngine_DetectOpportunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifiedTransaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MevEngineServer).DetectOpportunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: mevEngineDetectMethod,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MevEngineServer).DetectOpportunity(ctx, req.(*ClassifiedTransaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _MevEngine_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MevEngineServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: mevEngineStatusMethod,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MevEngineServer).GetStatus(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}
